
//----------------------------------------------------
// The following code was generated by CUP v0.11a beta 20060608
// Wed Nov 30 12:34:01 BRST 2016
//----------------------------------------------------

package analyzer;

/** CUP generated class containing symbol constants. */
public class sym {
  /* terminals */
  public static final int RESTO = 37;
  public static final int FUNCTION = 28;
  public static final int DIFERENTE = 44;
  public static final int MULTIPLICACAO = 34;
  public static final int REPEAT = 20;
  public static final int MAIORIGUAL = 40;
  public static final int FOR = 26;
  public static final int VIRGULA = 10;
  public static final int PONTO = 8;
  public static final int NOT = 50;
  public static final int AND = 45;
  public static final int MENORIGUAL = 39;
  public static final int IGUAL = 43;
  public static final int ELSEIF = 24;
  public static final int NIL = 47;
  public static final int PONTOS3 = 12;
  public static final int APAR = 2;
  public static final int ACOL = 4;
  public static final int OR = 46;
  public static final int PONTOS2 = 38;
  public static final int IN = 27;
  public static final int MAIS = 32;
  public static final int FCOL = 5;
  public static final int FPAR = 3;
  public static final int UNTIL = 21;
  public static final int EXPOENTE = 36;
  public static final int IF = 22;
  public static final int DPONTOS = 11;
  public static final int EOF = 0;
  public static final int RETURN = 30;
  public static final int MAIOR = 42;
  public static final int TRUE = 48;
  public static final int PVIRGULA = 9;
  public static final int error = 1;
  public static final int MENOS = 33;
  public static final int MENOR = 41;
  public static final int NUMBER = 16;
  public static final int BREAK = 31;
  public static final int TRALHA = 51;
  public static final int DIVISAO = 35;
  public static final int NAME = 14;
  public static final int ELSE = 25;
  public static final int ACHA = 6;
  public static final int WHILE = 19;
  public static final int FCHA = 7;
  public static final int THEN = 23;
  public static final int ATRIBUICAO = 13;
  public static final int END = 18;
  public static final int STRING = 15;
  public static final int LOCAL = 29;
  public static final int FALSE = 49;
  public static final int DO = 17;
}

