
//----------------------------------------------------
// The following code was generated by CUP v0.11a beta 20060608
// Mon Nov 14 19:03:04 BRST 2016
//----------------------------------------------------

package analyzer;

/** CUP generated class containing symbol constants. */
public class sym {
  /* terminals */
  public static final int ACOL = 4;
  public static final int FPAR = 3;
  public static final int ELSE = 28;
  public static final int THEN = 26;
  public static final int IN = 30;
  public static final int WHILE = 22;
  public static final int PONTO = 8;
  public static final int LOCAL = 32;
  public static final int TPONTOS = 12;
  public static final int DPONTOS = 11;
  public static final int VALUE = 14;
  public static final int RETURN = 33;
  public static final int END = 21;
  public static final int NAME = 15;
  public static final int APAR = 2;
  public static final int FUNCTION = 31;
  public static final int IF = 25;
  public static final int VIRGULA = 10;
  public static final int DO = 20;
  public static final int ATRIBUICAO = 13;
  public static final int STRING = 16;
  public static final int NUMBER = 19;
  public static final int EOF = 0;
  public static final int ELSEIF = 27;
  public static final int FCHA = 7;
  public static final int BREAK = 34;
  public static final int error = 1;
  public static final int UNTIL = 24;
  public static final int FCOL = 5;
  public static final int FOR = 29;
  public static final int ACHA = 6;
  public static final int PVIRGULA = 9;
  public static final int REPEAT = 23;
  public static final int BINOP = 17;
  public static final int UNOP = 18;
}

